// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: stockscraperpb/stockscraper.proto

package stockscraperpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FetchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stockscraperpb_stockscraper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stockscraperpb_stockscraper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_stockscraperpb_stockscraper_proto_rawDescGZIP(), []int{0}
}

func (x *FetchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FetchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price float32 `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stockscraperpb_stockscraper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stockscraperpb_stockscraper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_stockscraperpb_stockscraper_proto_rawDescGZIP(), []int{1}
}

func (x *FetchResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type MonitorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *MonitorRequest) Reset() {
	*x = MonitorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stockscraperpb_stockscraper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorRequest) ProtoMessage() {}

func (x *MonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stockscraperpb_stockscraper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorRequest.ProtoReflect.Descriptor instead.
func (*MonitorRequest) Descriptor() ([]byte, []int) {
	return file_stockscraperpb_stockscraper_proto_rawDescGZIP(), []int{2}
}

func (x *MonitorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MonitorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price float32 `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *MonitorResponse) Reset() {
	*x = MonitorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stockscraperpb_stockscraper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorResponse) ProtoMessage() {}

func (x *MonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stockscraperpb_stockscraper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorResponse.ProtoReflect.Descriptor instead.
func (*MonitorResponse) Descriptor() ([]byte, []int) {
	return file_stockscraperpb_stockscraper_proto_rawDescGZIP(), []int{3}
}

func (x *MonitorResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_stockscraperpb_stockscraper_proto protoreflect.FileDescriptor

var file_stockscraperpb_stockscraper_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x70, 0x62,
	0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65,
	0x72, 0x22, 0x22, 0x0a, 0x0c, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x0d, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x24, 0x0a, 0x0e,
	0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x27, 0x0a, 0x0f, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x32, 0x9e, 0x01, 0x0a, 0x0c,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x05,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x12, 0x1a, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x63, 0x72,
	0x61, 0x70, 0x65, 0x72, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72,
	0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4a, 0x0a, 0x07, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x1c, 0x2e, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x6e, 0x69, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x10, 0x5a, 0x0e,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stockscraperpb_stockscraper_proto_rawDescOnce sync.Once
	file_stockscraperpb_stockscraper_proto_rawDescData = file_stockscraperpb_stockscraper_proto_rawDesc
)

func file_stockscraperpb_stockscraper_proto_rawDescGZIP() []byte {
	file_stockscraperpb_stockscraper_proto_rawDescOnce.Do(func() {
		file_stockscraperpb_stockscraper_proto_rawDescData = protoimpl.X.CompressGZIP(file_stockscraperpb_stockscraper_proto_rawDescData)
	})
	return file_stockscraperpb_stockscraper_proto_rawDescData
}

var file_stockscraperpb_stockscraper_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stockscraperpb_stockscraper_proto_goTypes = []interface{}{
	(*FetchRequest)(nil),    // 0: stockscraper.FetchRequest
	(*FetchResponse)(nil),   // 1: stockscraper.FetchResponse
	(*MonitorRequest)(nil),  // 2: stockscraper.MonitorRequest
	(*MonitorResponse)(nil), // 3: stockscraper.MonitorResponse
}
var file_stockscraperpb_stockscraper_proto_depIdxs = []int32{
	0, // 0: stockscraper.stockscraper.Fetch:input_type -> stockscraper.FetchRequest
	2, // 1: stockscraper.stockscraper.Monitor:input_type -> stockscraper.MonitorRequest
	1, // 2: stockscraper.stockscraper.Fetch:output_type -> stockscraper.FetchResponse
	3, // 3: stockscraper.stockscraper.Monitor:output_type -> stockscraper.MonitorResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stockscraperpb_stockscraper_proto_init() }
func file_stockscraperpb_stockscraper_proto_init() {
	if File_stockscraperpb_stockscraper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stockscraperpb_stockscraper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stockscraperpb_stockscraper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stockscraperpb_stockscraper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonitorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stockscraperpb_stockscraper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonitorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stockscraperpb_stockscraper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stockscraperpb_stockscraper_proto_goTypes,
		DependencyIndexes: file_stockscraperpb_stockscraper_proto_depIdxs,
		MessageInfos:      file_stockscraperpb_stockscraper_proto_msgTypes,
	}.Build()
	File_stockscraperpb_stockscraper_proto = out.File
	file_stockscraperpb_stockscraper_proto_rawDesc = nil
	file_stockscraperpb_stockscraper_proto_goTypes = nil
	file_stockscraperpb_stockscraper_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StockscraperClient is the client API for Stockscraper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StockscraperClient interface {
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	Monitor(ctx context.Context, in *MonitorRequest, opts ...grpc.CallOption) (Stockscraper_MonitorClient, error)
}

type stockscraperClient struct {
	cc grpc.ClientConnInterface
}

func NewStockscraperClient(cc grpc.ClientConnInterface) StockscraperClient {
	return &stockscraperClient{cc}
}

func (c *stockscraperClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, "/stockscraper.stockscraper/Fetch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockscraperClient) Monitor(ctx context.Context, in *MonitorRequest, opts ...grpc.CallOption) (Stockscraper_MonitorClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Stockscraper_serviceDesc.Streams[0], "/stockscraper.stockscraper/Monitor", opts...)
	if err != nil {
		return nil, err
	}
	x := &stockscraperMonitorClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Stockscraper_MonitorClient interface {
	Recv() (*MonitorResponse, error)
	grpc.ClientStream
}

type stockscraperMonitorClient struct {
	grpc.ClientStream
}

func (x *stockscraperMonitorClient) Recv() (*MonitorResponse, error) {
	m := new(MonitorResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StockscraperServer is the server API for Stockscraper service.
type StockscraperServer interface {
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	Monitor(*MonitorRequest, Stockscraper_MonitorServer) error
}

// UnimplementedStockscraperServer can be embedded to have forward compatible implementations.
type UnimplementedStockscraperServer struct {
}

func (*UnimplementedStockscraperServer) Fetch(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (*UnimplementedStockscraperServer) Monitor(*MonitorRequest, Stockscraper_MonitorServer) error {
	return status.Errorf(codes.Unimplemented, "method Monitor not implemented")
}

func RegisterStockscraperServer(s *grpc.Server, srv StockscraperServer) {
	s.RegisterService(&_Stockscraper_serviceDesc, srv)
}

func _Stockscraper_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockscraperServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stockscraper.stockscraper/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockscraperServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockscraper_Monitor_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MonitorRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StockscraperServer).Monitor(m, &stockscraperMonitorServer{stream})
}

type Stockscraper_MonitorServer interface {
	Send(*MonitorResponse) error
	grpc.ServerStream
}

type stockscraperMonitorServer struct {
	grpc.ServerStream
}

func (x *stockscraperMonitorServer) Send(m *MonitorResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Stockscraper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stockscraper.stockscraper",
	HandlerType: (*StockscraperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _Stockscraper_Fetch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Monitor",
			Handler:       _Stockscraper_Monitor_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "stockscraperpb/stockscraper.proto",
}
